INSERT INTO burgers (burger_name) VALUES ('If Looks Could Kale Burger');
INSERT INTO burgers (burger_name) VALUES ('A Leek of Their Own Burger');
INSERT INTO burgers (burger_name) VALUES ('Texas Chainsaw Massa-curd Burger (comes with cheese curds)');
INSERT INTO burgers (burger_name) VALUES ('Parma Parma Parma Chameleon Burger (with Parmesan crisp)');
INSERT INTO burgers (burger_name) VALUES ('I Fought the Slaw Burger (And the Slaw Won)');
INSERT INTO burgers (burger_name) VALUES ('Tarragon in Sixty Seconds Burger');
INSERT INTO burgers (burger_name) VALUES ('Blue Is the Warmest Cheese Burger');
INSERT INTO burgers (burger_name) VALUES ('Camembert-ly Legal Burger');
INSERT INTO burgers (burger_name) VALUES ('Bohemian Radishy Burger');
INSERT INTO burgers (burger_name) VALUES ('Little Swiss Bunshine (comes on a buttered bun)');
INSERT INTO burgers (burger_name) VALUES ('Poblano Picasso Burger');
INSERT INTO burgers (burger_name) VALUES ('I Know Why the Cajun Burger Sings');
INSERT INTO burgers (burger_name) VALUES ('Kale Mary Burger (served with kale)');
INSERT INTO burgers (burger_name) VALUES ('Shoot Out at the Okra Corral Burger');
INSERT INTO burgers (burger_name) VALUES ('Bleu by You Burger (with locally sourced bleu cheese)');
